### PR TITLE
Send image base64 to backend

### LINKED ISSUE #137: Send image data on create project flow
When user creates a project, the image field is path to image. We should fill that entry with image data (base64 type maybe)

### PR DESCRIPTION
**Pull request by brymut**
Send image ~blob~ base64 to backend, dont upload to pinata. And remove Pinata front end stuffResolves #137

### CODE REVIEW

**Comment by aminlatifi** [comment]
@brymut Can graphql (apollo server) transfer file data in blob format? Most of practices I saw encoded data to base64.

**Comment by geleeroyale** [comment]
This is pending further commits by Amin.

**Comment by brymut** [comment]
Ohh, I didn't know, which changes/additions will be made to this? @geleeroyale @aminlatifi

**Comment by geleeroyale** [comment]
I am unsure - Amin only asked to wait before merging and said he would like to add something before we merge this.

**Comment by aminlatifi** [comment]
@brymut I would implement any changes that would be needed

**Comment by geleeroyale** [comment]
@aminlatifi But can you detail what is needed that blocks this PR?

**Comment by aminlatifi** [comment]
Nothing

**Comment by aminlatifi** [comment]
I may change the way image data is passed

**Comment by brymut** [comment]
I don't mind switching anything over that you can point out or if you have anything more specific in mind I'll just leave this open.

**Comment by brymut** [comment]
I'll just merge this and the change can be made later, I need this in another PR

**Pull request merged**
