### PR TITLE
Dev/slug implementation

### PR DESCRIPTION
**Pull request by mateodaza**
In case that the project page is not built statically it will be fetch through the slug generated on creation

It solves #55 

A question came up from this, I noticed that the slugs generated in build fetches the projects from https://graph.topia.us, shall we change that to our own graph and sync the slugs with the ones that are created on addProject function?

### CODE REVIEW

**Comment by geleeroyale** [comment]
Yes please put that in. It should not be able to parse that Covid campaign anymore then. Which is good! You can kick that as well since it actually blocks the project from compiling on Windows. The only successfully posted campaign for now is Amin's Spoon Man test campaign - maybe switch it out with that one for now?

**Comment by mateodaza** [comment]
Before merging this we need the impact graph to be updated => [PR](https://github.com/Giveth/impact-graph/pull/13)

**Comment by geleeroyale** [comment]
This is an awesome contribution - Thanks so much - looks really great on test drive. Are we ready to merge this yet, or are you waiting for above referenced changes in `impact-graph`?

**Comment by mateodaza** [comment]
The graph is ready in the current PR. I just wanted to wait to discuss if something else was needed to merge 🙌🏼

**Comment by geleeroyale** [comment]
Alright - we can merge it together during devcall - then you can show us around immediately after if you want.

**Review by geleeroyale — APPROVED** [review]
Great contribution! This fixes many long standing issues and finally opens up the whole `creat project` flow with project descriptions. Very exciting - this is a big push towards MVP.

**Pull request merged**
